var mutex_lock,mutex_unlock;!function(lib_name,crystal_args,namespace,ua){var pageStartTime
;window.QosSS&&QosSS.t?pageStartTime=QosSS.t[0]:window.QosSS&&QosSS.tQueue?pageStartTime=QosSS.tQueue[0]:window.QosS&&QosS.G?pageStartTime=QosS.G.startTime||QosS.G.st:window.QosS&&QosS.Global?pageStartTime=QosS.Global.startTime:window.d0&&window.d0.getTime&&(
pageStartTime=window.d0.getTime());var DURATION_LOAD_JS=pageStartTime&&window.TIME_BEFORE_LOAD_CRYSTAL?window.TIME_BEFORE_LOAD_CRYSTAL-pageStartTime:-1;Array.prototype.indexOf||(Array.prototype.indexOf=function(searchElement,fromIndex){if(null==this
)throw new TypeError('"this" is null or not defined');var length=this.length>>>0;for(fromIndex=+fromIndex||0,Math.abs(fromIndex)===1/0&&(fromIndex=0),fromIndex<0&&(fromIndex+=length)<0&&(fromIndex=0);fromIndex<length;fromIndex++)if(
this[fromIndex]===searchElement)return fromIndex;return-1}),Array.prototype.forEach||(Array.prototype.forEach=function(callback,thisArg){var i;thisArg=thisArg||null;var len=this.length;for(i=0;i<len;i++)callback.call(thisArg,this[i],i,this)}),Date.now||(
Date.now=function(){return(new Date).getTime()});var Uuids={get:function(){for(var s=[],i=0;i<36;i++)s[i]="0123456789abcdef".substr(Math.floor(16*Math.random()),1);return s[14]="4",s[19]="0123456789abcdef".substr(3&s[19]|8,1),s[8]=s[13]=s[18]=s[23]="-",
s.join("")},getReqId:function(){return this.get().replace(/[-]/g,"")},getCurrentPageReqId:function(){return this.cprid?this.cprid:this.cprid=this.getReqId()}};namespace.Uuids=Uuids;var OBJ_CSS_TESTER_EL=document.createElement("div")
;function testCssPositionFixed(){return 6!==ua.ie}function testCssMozPrefix(){return"MozBinding"in OBJ_CSS_TESTER_EL.style}function testCssRgba(){var originalColor=OBJ_CSS_TESTER_EL.style.color;try{return OBJ_CSS_TESTER_EL.style.color="rgba(0,0,0,0.5)",
OBJ_CSS_TESTER_EL.style.color!==originalColor}catch(e){return!1}}var FeatureDetector=namespace.FeatureDetector={cssPositionFixed:testCssPositionFixed(),cssMozPrefix:testCssMozPrefix(),cssRgba:testCssRgba()},CrystalPageSpeed={tagMap:{},time:function(tag,
time){var t=time||Date.now();this.tagMap[tag]||(this.tagMap[tag]={});var tagRecord=this.tagMap[tag];-1===tagRecord.start||-1===tagRecord.end||tagRecord.duration||tagRecord.start&&!tagRecord.end||(tagRecord.start=t,tagRecord.end=void 0)},timeEnd:function(
tag){var endTime=Date.now();if(tag=this.tagMap[tag])return-1===tag.start||-1===tag.end||tag.duration||tag.end||(tag.end=endTime,tag.duration=-1===tag.start?-1:endTime-tag.start),tag.duration},setDuration:function(tag,duration){this.tagMap[tag]={start:-1,
end:-1,duration:duration}},flush:function(pingSender){if(!this.isDirtyData()){var k,params={},envInfo=this.getEnvInfo();for(k in envInfo)params[k]=envInfo[k];for(k in this.tagMap)this.tagMap[k].duration+""&&(
"lview-l.qq.com"===k?params.lview=this.tagMap[k].duration:params[k]=this.tagMap[k].duration);0===params.err&&(void 0===params.ping&&(params.err=6001),void 0===params.cdn&&(params.err=5001),void 0===params.lview&&(params.err=4001),void 0===params.dr&&(
params.err=3001),-1===params.loadjs&&(params.err=1001)),params.all=(new Date).getTime()-this.tagMap.js.start,params.all<1e3*crystal_args.lview_time_out&&4002===params.err&&(delete params.lview,params.err=4004),(pingSender=pingSender||sendPing)(
"//dp3.qq.com/stdlog?bid=crystal&"+serializeQuery(params))}this.flush=function(){}},getEnvInfo:function(){if(!this.envInfo){var d=this.getBrowserDimension(),dmMatch=location.href.match(/\/\/([^\?\/]*)\/?\??/),dm=dmMatch&&dmMatch[1]?dmMatch[1]:-1,
ishttps=-1<location.protocol.indexOf("https")?1:0;this.envInfo={err:0,pid:"statusreport",host:dm,ua:browsersniffer(navigator.userAgent),cv:namespace.version,fv:namespace.getFlashVersion(),bw:d.width,bh:d.height,sw:window.screen.width,
sh:window.screen.height,net:0,val1:location.href,reqid:namespace.Uuids.getCurrentPageReqId(),ishttps:ishttps}}return this.envInfo},getBrowserDimension:function(){var r={width:-1,height:-1},myHeight=(document.documentElement,document.body,-1),myWidth=-1
;return"number"==typeof window.innerWidth?(myWidth=window.innerWidth,myHeight=window.innerHeight):document.documentElement&&(document.documentElement.clientWidth||document.documentElement.clientHeight)?(myWidth=document.documentElement.clientWidth,
myHeight=document.documentElement.clientHeight):document.body&&(document.body.clientWidth||document.body.clientHeight)&&(myWidth=document.body.clientWidth,myHeight=document.body.clientHeight),r.width=myWidth,r.height=myHeight,r},
setEnvInfoProperty:function(propName,propValue){this.getEnvInfo()[propName]=propValue},isDirtyData:function(){var i,testTags=["loadjs","js","dr"];for(i=0;i<testTags.length;i++){var t=this.tagMap[testTags[i]];if(t&&t.duration&&t.duration<-1)return!0}
return!1},on:function(el,type,handler){return document.addEventListener?el.addEventListener(type,handler,!1):el.attachEvent("on"+type,handler),handler},isElementInViewport:function(el,adWidth,adHeight){try{if(!el.getBoundingClientRect)throw new Error(
"Method getBoundingClientRect is not supported to detect advertisement click.");var rect=el.getBoundingClientRect()}catch(e){return!1}var adArea=parseInt(adWidth)*parseInt(adHeight);var top=rect.top,left=rect.left,bottom=rect.bottom,right=rect.right,
winHeight=window.innerHeight||document.documentElement.clientHeight,winWidth=window.innerWidth||document.documentElement.clientWidth;return adArea/2<=(top<0?adHeight+top:winHeight<bottom?adHeight-bottom+winHeight:adHeight)*(
left<0?adWidth+left:winWidth<right?adWidth-right+winWidth:adWidth)},adClickMap:{},registerClick:function(adEl,clickableEl,adData){if(crystal_args.jsProfileOpen){var loc=adData.loc,oid=adData.oid;if(!this.adClickMap[loc]){this.adClickMap[loc]={loc:loc,
adEl:adEl,adData:adData,visibleStartTime:adData.fodder[0]&&this.isElementInViewport(adEl,adData.fodder[0].width,adData.fodder[0].height)?Date.now():null};var self=this;this.on(clickableEl,"click",function(){var now=Date.now(),
visibleStartTime=self.adClickMap[loc].visibleStartTime;sendPing(crystal_args.mo_ad_click_url+"?"+serializeQuery({loc:loc,oid:oid,reqid:namespace.Uuids.getCurrentPageReqId(),stay:pageStartTime?now-pageStartTime:-1,
click:visibleStartTime?now-visibleStartTime:-1}))})}}},initVisibleAdDetectorEvent:function(){var self=this;function handler(){var k,v;for(k in self.adClickMap)(v=self.adClickMap[k]).adData.fodder[0]&&self.isElementInViewport(v.adEl,v.adData.fodder[0].width
,v.adData.fodder[0].height)&&(v.visibleStartTime=Date.now())}this.on(window,"DOMContentLoaded",handler),this.on(window,"load",handler),this.on(window,"scroll",handler),this.on(window,"resize",handler)}},Cps=namespace.cps=CrystalPageSpeed,lib_name,lib_name
;if(Cps.initVisibleAdDetectorEvent(),Cps.setDuration("loadjs",DURATION_LOAD_JS),Cps.time("js",window.TIME_BEFORE_LOAD_CRYSTAL?window.TIME_BEFORE_LOAD_CRYSTAL:-1),Cps.timeEnd("js"),Cps.time("dr"),void 0===window[lib_name]){
window[lib_name]=window.crystal2=window.AD2=namespace;var PrivacyTag={privateOriganalIcon:function(dsp_name,private_link,css){var privacyTag=this,privateIcon=namespace.dom.createElement({position:"absolute",width:"18px",height:"18px",right:"0px",
bottom:"0px",cursor:"pointer","z-index":20,background:"url("+namespace.resource("privacy/white_icon.png")+") no-repeat"},{"class":"absolute"},"div");return css&&namespace.dom.setStyle(privateIcon,css),namespace.evt.on(privateIcon,"mouseover",function(e){
var privateName=privacyTag.addPrivateTag(dsp_name,private_link,css);privateIcon.parentNode.appendChild(privateName),privateIcon.parentNode.removeChild(privateIcon)}),namespace.evt.on(privateIcon,"click",function(e){window.open(private_link)}),privateIcon},
privateMouseOverIcon:function(css){var privateIcon=namespace.dom.createElement({position:"absolute",width:"18px",height:"18px",right:"0px",bottom:"0px",cursor:"pointer","z-index":20,background:"url("+namespace.resource("privacy/blue_icon.png"
)+") no-repeat"},{"class":"absolute"},"div");return css&&namespace.dom.setStyle(privateIcon,css),privateIcon},privateDspName:function(dsp_name,private_link,css){var dspName="  "+dsp_name+" ",privateName=namespace.dom.createElement({position:"absolute",
width:"auto","font-size":"12px","line-height":"18px",height:"18px",right:"18px",bottom:"0px",color:"#FFF",cursor:"pointer","z-index":20,"white-space":"pre",background:"url("+namespace.resource("privacy/black_bg.png")+") no-repeat"},{"class":"absolute"},
"div",dspName);if(css){var dspNameCss=JSON.parse(JSON.stringify(css));dspNameCss.width="auto",dspNameCss.right=parseInt(css.right.split("px")[0])+18+"px",namespace.dom.setStyle(privateName,dspNameCss)}return privateName},addPrivateTag:function(dsp_name,
private_link,css){var privacyTag=this,privateTag=namespace.dom.createElement({},{},"div"),privateName=privacyTag.privateDspName(dsp_name,private_link,css),privateIcon=privacyTag.privateMouseOverIcon(css);return privateTag.appendChild(privateName),
privateTag.appendChild(privateIcon),namespace.evt.on(privateTag,"mouseout",function(e){((e=e||window.event).relatedTarget||e.toElement)!==privateName&&(privateTag.parentNode.appendChild(privacyTag.privateOriganalIcon(dsp_name,private_link,css)),
privateTag.parentNode.removeChild(privateTag))}),namespace.evt.on(privateTag,"click",function(e){window.open(private_link)}),privateTag},reportIcon:function(el,oid){var report_link=namespace.getProtocol("//ra.gtimg.com/web/jsproxy/reportfakead.html"),
reportIcon=namespace.dom.createElement({position:"absolute",width:"24px",height:"16px",left:"26px",bottom:"0px",cursor:"pointer",display:"none","z-index":20,background:"url("+namespace.resource("res/icon/report_default_new.png")+") no-repeat top"},{
"class":"absolute"},"div");return namespace.evt.on(reportIcon,"click",function(e){var timestamp=(new Date).getTime();window.open(report_link+"?oid="+oid+"&timestamp="+timestamp)}),namespace.evt.on(reportIcon,"mouseover",function(e){namespace.dom.setStyle(
reportIcon,{background:"url("+namespace.resource("res/icon/report_hover_new.png")+") no-repeat top"})}),namespace.evt.on(reportIcon,"mouseout",function(e){namespace.dom.setStyle(reportIcon,{background:"url("+namespace.resource(
"res/icon/report_default_new.png")+") no-repeat top"})}),namespace.evt.on(el,"mouseover",function(e){namespace.dom.setStyle(reportIcon,{display:"block"})}),namespace.evt.on(el,"mouseout",function(e){((e=e||window.event).relatedTarget||e.toElement
)!==reportIcon&&namespace.dom.setStyle(reportIcon,{display:"none"})}),reportIcon}},Pt=namespace.pt=PrivacyTag,cpm_prefix_process=(crystal_toberemove=["Finance_Width1","Finance_Width2","Finance_Rectangle","Finance_Width3","Finance_Width4","Finance_Width5",
"Finance_2nd_Width1","Finance_2nd_Rectangle1","Finance_2nd_bottom_Width","stock_Width1","stock_Rectangle","stock_Width2","stock_Width3","F_Width1_N","F_UpRight1","F_D_Width1","health_width1","health_width2","health_Rectangle1","health_Rectangle2",
"Edu_Width1","Edu_Width2","Edu_Width3","Edu_Width4","Edu_HP_Rectangle","Edu_2nd_Width1","Edu_KY_Width1","Tech_Width1","Tech_bottom_Width","Tech_2nd_Width1","Tech_2nd_Width2","Tech_Rectangle1","Tech_Rectangle2","Auto_Width1","Auto_Width2","Auto_Width3",
"Auto_Width4","Auto_Width5","Auto_Width6","Auto_Button1","auto_button2","Auto_Button3","Auto_Button4","Auto_Button5","Auto_2nd_Width1","Auto_2nd_Width2","Fashion_Width1","Fashion_Width2","Fashion_Width3","Fashion_Width4","Fashion_Width5","Fashion_Button1",
"Fashion_button2","Fashion_button3","Fashion_pic_Width2","Fashion_2nd_Width1","Fashion_2nd_Width2","Digital_Width1","Digital_Width2","Digital_Width5","Digital_Rectangle1","Digital_Rectangle2","Digi_2nd_Width1","Digi_2nd_Width2","Sports_Width1A",
"News_Width1","News_Rectangle","News_Rectangle2","News_Rectangle3","News_Width2","News_Width3","News_skyscraper","News_Width4","News_Pic_Width2","News_2nd_Width1","News_2nd_Width2","Gamezone_Width1","Gamezone_Width2","Gamezone_Width3","Gamezone_Width4",
"Game_bottom_Width","Game_2nd_Width1","Game_2nd_Width2","Ent_Button1","Ent_Rectangle1","Ent_Rectangle2","Ent_Width1","Ent_Width2","Ent_Width3","Ent_Width4","Ent_Pic_Width2","Ent_2nd_Width1","Ent_2nd_Width2","Ent_2nd_Rectangle1","Music_Upright",
"ent_ZL_Rectangle","ent_ZL_Width1","ent_ZL_Width2","Baby_Width2","Baby_Width3","Baby_Width4","Baby_Rectangle","stock_2nd_Width1","stock_2nd_Width2","Music_Width1","Music_Width2","QQlive_SP_HP_Width1","QQlive_SP_HP_Width2","QQlive_SP_HP_bottom_Width",
"QQlive_SP_DSJ_banner1","QQlive_SP_DSJ_banner2","QQlive_SP_DSJ_banner3","QQlive_SP_DYPD_Width1","QQlive_SP_DYPD_Width2","QQlive_SP_DYPD_Width3","QQlive_SP_ZY_banner1","QQlive_SP_ZY_banner2","QQlive_SP_ZY_banner3","QQlive_SP_ZY_banner4",
"QQlive_SP_YMJ_Width1","QQlive_SP_YMJ_Width2","QQlive_SP_YMJ_Width3","QQlive_SP_HJ_Width1","QQlive_SP_HJ_Width2","QQlive_SP_GX_Width1","QQlive_SP_Game_Width1","QQlive_SP_Game_Width2","QQlive_SP_Game_Width3","QQlive_SP_WDY_Width1","QQlive_SP_YY_Width1",
"QQlive_SP_jlp_Width1","QQlive_SP_jlp_Width2","QQlive_SP_dm_Width1","QQlive_SP_dm_Width2","QQlive_SP_YL_Width1","QQlive_SP_SR_Width1","QQlive_SP_SR_Width2","QQlive_SP_XW_Width1","QQlive_SP_XW_Width2","QQlive_SP_SSPD_Width1","QQlive_SP_YE_Width1",
"QQlive_SP_NN_BF_bottom_Width"],function(){for(var i=0,l=crystal_toberemove.length;i<l;i++){var node=document.getElementById(crystal_toberemove[i]);node&&node.parentNode&&node.parentNode.removeChild(node)}}),crystal_toberemove;namespace.httpProtocolList={
"ra.gtimg.com":!1,"lb.l.qq.com":!1,"p3.l.qq.com":!1,"bs.l.qq.com":!1,"t.l.qq.com":!1,"img1.gtimg.com":!1,"m.l.qq.com":!1,"mat1.gtimg.com":!1,"sac.l.qq.com":!1,"wa.gtimg.com":!1,"dp3.qq.com":!1,"adsrich.qq.com":!1,"connect.l.qq.com":!1,"imgcache.qq.com":!1,
"share.v.t.qq.com":!1,"t.qq.com":!1,"sports.qq.com":!1,"c.l.qq.com":!1,"w.l.qq.com":!1,"p.l.qq.com":!1,"x.l.qq.com":!1,"l.qq.com":!1,"user.qzone.qq.com":!1,"bizapp.qq.com":!1},namespace.getProtocol=function(url){if(!url)return"";0===url.indexOf("http:")&&(
url=url.split("http:")[1]),0===url.indexOf("https:")&&(url=url.split("https:")[1]);var domain=-1<url.indexOf("/",2)?url.substring(2,url.indexOf("/",2)):url.substring(2,1e3)
;return void 0!==namespace.httpProtocolList[domain]&&!0===namespace.httpProtocolList[domain]&&(url="http:"+url),url},crystal_args.file_path=namespace.getProtocol(crystal_args.file_path),crystal_args.ext_path=namespace.getProtocol(crystal_args.ext_path),
crystal_args.lview_template=namespace.getProtocol(crystal_args.lview_template),crystal_args.ping_template=namespace.getProtocol(crystal_args.ping_template),crystal_args.mo_page_url=namespace.getProtocol(crystal_args.mo_page_url),
crystal_args.mo_ad_click_url=namespace.getProtocol(crystal_args.mo_ad_click_url),crystal_args.share_dialogue_url=namespace.getProtocol(crystal_args.share_dialogue_url),crystal_args.privacyImg=namespace.getProtocol(crystal_args.privacyImg),
crystal_args.sac_req_url=namespace.getProtocol(crystal_args.sac_req_url),crystal_args.extension_js_src=namespace.getProtocol(crystal_args.extension_js_src),namespace.cpm_prefix_process=cpm_prefix_process,namespace.version="qq_v5.0Beta01",
namespace.resourceInvalid=null,namespace.display_orders=[],eval(namespace.output(lib_name)),namespace.crystal_args=crystal_args;var log=namespace.log=function(params){},refs=namespace.__images=[],sendPing=function(url,norandom){var img=new Image(1,1);if(
!norandom){var constr="?";-1!=url.indexOf("?")&&(constr="&"),url=url+constr+Math.random()}return-1<url.indexOf("[timestamp]")&&(url=url.replace("[timestamp]",Math.round((new Date).getTime()/1e3))),img.src=url,refs.push(img),this},report_ua=function(){for(
var i in ua)if(0!=ua[i])return i+ua[i]}(),importScript=namespace.importScript=function(url,callback,charset,errorCallback){var script=document.createElement("script");script.src=url,charset&&(script.charset=charset),callback&&(
ua.ie?script.onreadystatechange=function(){var rs=this.readyState;"loaded"!==rs&&"complete"!==rs||callback()}:script.onload=callback),errorCallback&&"onerror"in script&&(script.onerror=errorCallback),document.getElementsByTagName("head")[0].appendChild(
script)},channel;try{var url_search=location.search,channel_match=location.href.match(/([\w\.]+)\.qq\.com/),channel_mapping={"cp":"sports","sport":"sports","fcbarcelona":"sports","college":"edu","zhiyun":"sports","kbs.sports":"sports","data.auto":"auto",
"thr":"ent","space":"tech","view.news":"coral","video.coral":"coral","mil":"news","space":"tech"};if(channel=namespace.channel=(channel_match&&channel_match[1]).toLowerCase(),-1<location.href.indexOf(namespace.getProtocol("//sports.qq.com/nba"))&&(
channel=namespace.channel="nba"),window.ARTICLE_INFO&&window.ARTICLE_INFO.tpl&&window.ARTICLE_INFO.tpl.dev&&"nba"===window.ARTICLE_INFO.tpl.dev&&(channel=window.ARTICLE_INFO.tpl.dev),channel_mapping[channel]&&(channel=channel_mapping[channel]),
"v"===channel||"test.v"===channel)if(window.V_PAGE_INFO&&void 0!==window.V_PAGE_INFO.channel)channel="v_"+window.V_PAGE_INFO.channel;else{var pathname=location.pathname;if(1<pathname.length)if("/x/2017/"==pathname)channel="v_www";else if(
-1<pathname.indexOf("/tv/yingmei/"))channel="v_yingmei";else if(-1<pathname.indexOf("/tv/korea/"))channel="v_korea";else if(-1<pathname.indexOf("/x/cover/")||-1<pathname.indexOf("/cover/")){var v_chl_mapping={1:"movie",2:"tv",3:"cartoon",4:"sports",
5:"ent",6:"games",8:"news",9:"doco",10:"variety",11:"variety",12:"news",13:"variety",15:"sports",17:"sports",18:"news",19:"variety",21:"sports",22:"music",23:"news",24:"finance",25:"fashion",26:"travel",27:"education",28:"tech",29:"auto",30:"house",
31:"life",33:"sports",34:"sports",35:"sports",37:"class",38:"music",43:"fun",45:"rushidao",46:"movie",49:"education",60:"baby",97:"sports",98:"movie",99:"variety",100:"education",101:"sports",102:"sports",103:"videoplus",104:"news",105:"paike",106:"child",
200:"music"};channel=window.COVER_INFO&&window.COVER_INFO.typeid&&v_chl_mapping[COVER_INFO.typeid]?"v_"+v_chl_mapping[COVER_INFO.typeid]:"v_x"}else{var reg=new RegExp(/\/[a-z]*\//);pathname=pathname.match(reg)[0],channel="v_"+pathname.substring(1,
pathname.length-1)}else channel="v_www"}var matchResult=location.href.match(/https?\:\/\/.*\.qq\.com\/ch2?\/([^\/]*)\/?/);matchResult&&(channel=matchResult[1],namespace.channel=channel);var ref=document.referrer,refResult=ref.match(
/https?\:\/\/.*\.qq\.com\/ch?\/([^\/]*)\/?/);refResult?null===channel.match(/[^a-zA-Z_\-\:0-9]/)&&(channel=refResult[1],namespace.channel=channel):void 0!==window.DATA&&window.DATA.hasOwnProperty("catalog1")&&(channel=window.DATA.catalog1,
namespace.channel=channel)}catch(e){}"undefined"!=typeof page_channel&&(channel=page_channel||channel);var IPingBase={append:doNothing,flush:doNothing,touch:sendPing};document.documentElement.contains?namespace.contains=function(a,b){return a!==b&&(
!a.contains||a.contains(b))}:document.documentElement.compareDocumentPosition?namespace.contains=function(a,b){return!!(16&a.compareDocumentPosition(b))}:namespace.contains=function(){return!1},namespace.sns_pingurl=sns_pingurl;var fp11input=null,
pageinfo=namespace.pageinfo={"info":null,order:[]},limitchar=function(str,maxchar){for(var cl=str.length,ret="",olen=0,i=0;i<cl;i++){var t=encodeURIComponent(str.substr(i,1));(olen+=t.length)<maxchar&&(ret+=t)}return ret},encodeURIComLimit=function(str,
maxchar){var encodeStr=encodeURIComponent(str);if(encodeStr.length>maxchar)for(var isOver=!1;!isOver;){encodeStr=encodeStr.substr(0,maxchar);try{decodeURIComponent(encodeStr),isOver=!0}catch(e){maxchar--}}return encodeStr},isFromDiscuz=function(fromStr){
return!!fromStr&&(-1<fromStr.indexOf("/f/discuz")||-1<fromStr.indexOf("search.php?"))},collectInfo=function(mode){var info=null;if(null!=namespace.pageinfo.info)info=namespace.pageinfo.info;else{var keywords="",title="",refer="",soso="";each(
document.getElementsByTagName("meta"),function(o,i){"keywords"==o.getAttribute("name")&&(keywords=o.getAttribute("content")||"")});try{title=document.getElementsByTagName("title")[0].innerHTML,refer=document.referrer;var regex=new RegExp(
"(?:yahoo.+?[?|&]p=|openfind.+?query=|google.+?q=|lycos.+?query=|onseek.+?keyword=|search.tom.+?word=|search.qq.com.+?word=|zhongsou.com.+?word=|search.msn.com.+?q=|yisou.com.+?p=|sina.+?word=|sina.+?query=|sina.+?_searchkey=|sohu.+?word=|sohu.+?key_word=|sohu.+?query=|163.+?q=|baidu.+?wd=|baidu.+?kw=|baidu.+?word=|3721.com.+?p=|Alltheweb.+?q=|soso.+?w=|115.+?q=|youdao.+?q=|sogou.+?query=|bing.+?q=|114.+?kw=|/f/discuz.+q=|/.+/search.php.+?kw=)([^&]*)"
),result=refer.match(regex);if(result){var from=result[0];if(0===result[1].indexOf("%25")&&(result[1]=decodeURIComponent(result[1])),isFromDiscuz(from))refer="discuz%7C"+result[1];else try{refer=result[0].substr(0,result[0].indexOf("."))+"%7C"+result[1]
}catch(e){refer=result[0].substr(0,result[0].indexOf("."))+"%7C"+result[1]}}else refer=""}catch(e){}keywords=limitchar(keywords,360),title=limitchar(title,180),refer=refer.substr(0,90),soso=limitchar(soso,90),info={"k":keywords,"t":title,"r":refer,"s":soso
},namespace.pageinfo.info=info}return 1==mode?"&k="+info.k+"&t="+info.t+"&r="+info.r+"&s="+info.s:info};window[lib_name].ActionPing={actionCodeDictionary:{"RICH_COUPLET_MOUSEOVER":40006,"RICH_COUPLET_MOUSEOUT":40005,"RICH_COUPLET_CLOSE":40001,
"RICH_COUPLET_SWITCH":40009,"RICH_COUPLET_SHOW":40008,"EXTEND_TURNER_EXTEND":60003,"EXTEND_TURNER_REDUCE":60004},urlTemplate:namespace.getProtocol("//m.l.qq.com?t=s&mid={mid}&actid={actid}&subactid={subactid}&aver={aver}&oid={oid}&locid={loc}"),
_requestByImg:function(url,norandom){var img=new Image(1,1);if(!norandom){var constr="?";-1!=url.indexOf("?")&&(constr="&"),url=url+constr+Math.random()}return img.src=url,refs.push(img),this},send:function(parameter){
var actionId=this.actionCodeDictionary[parameter.actionCode]||parameter.actionId;parameter.actid=actionId,parameter.mid=parameter.mid||parameter.oid,parameter.subactid=parameter.subactid||0;var currentUrl=format(this.urlTemplate,parameter)
;this._requestByImg(currentUrl)}};var DataStorage=window[lib_name].DataStorage=(mod="DataStorage",tests={},tests.localstorage=function(){try{return localStorage.setItem(mod,mod),localStorage.removeItem(mod),!0}catch(e){return!1}},tests.userdata=function(){
try{return(userDataDomElement=document.createElement("input")).type="hidden",void 0!==userDataDomElement.addBehavior&&(userDataDomElement.addBehavior("#default#userData"),document.body.insertBefore(userDataDomElement,document.body.firstChild),
userDataDomElement.load(mod),userDataDomElement.setAttribute(mod,mod),userDataDomElement.save(mod),userDataDomElement.load(mod),userDataDomElement.expires=new Date(315532799e3).toUTCString(),!0)}catch(e){return!1}},tests.localstorage()?{setItem:function(
key,value){localStorage.setItem(key,value)},getItem:function(key){return localStorage.getItem(key)},removeItem:function(key){localStorage.removeItem(key)}}:tests.userdata()&&ua.ie<9?{defExps:525600,valueKeyStr:"savedValue",setItem:function(key,value,
expireTime){try{userDataDomElement.load(key),userDataDomElement.setAttribute(this.valueKeyStr,value),expireTime=expireTime||this.defExps,userDataDomElement.expires=generateExpireDate(expireTime),userDataDomElement.save(key)}catch(ex){}},getItem:function(
key){try{return userDataDomElement.load(key),userDataDomElement.getAttribute(this.valueKeyStr)}catch(ex){return null}},removeItem:function(key){this.setItem(key,!1,-this.defExps)}}:{deserializeString:function(assign_token,pair_separator,need_last,
need_decode){var decode=need_decode?decodeURIComponent:function(k){return k};return function(s){var ret={};need_last&&(s=s.replace(new RegExp(pair_separator+"$"),""));for(var pairArray=s.split(pair_separator),i=0;i<pairArray.length;i++){
var key_value=pairArray[i].split(assign_token);ret[decode(key_value[0])]=decode(key_value[1])}return ret}},setItem:function(key,value,expireTime){var text=key+"="+value;expireTime&&(text+="; expires="+generateExpireDate(expireTime)),text+="; path=/",
document.cookie=text},getItem:function(key){if(key)return this.deserializeString("=","; ",!1,!1)(document.cookie)[key]},removeItem:function(key){this.setItem(key,"",-1)}}),userDataDomElement,mod,tests,default_Ad_local=namespace.DataStorage.getItem(
"crystal_defaultAd"),defaultAdData={createTime:0},getDefaultAdDataFirstTime=!0,PageType=(home=["//www.qq.com","//finance.qq.com","//health.qq.com","//edu.qq.com","//tech.qq.com","//auto.qq.com","//fashion.qq.com","//digi.tech.qq.com","//sports.qq.com",
"//cul.qq.com","//news.qq.com","//games.qq.com","//ent.qq.com","//baby.qq.com","//astro.fashion.qq.com","//college.qq.com","//sport.qq.com","//stock.qq.com","//sports.qq.com/nba"],function(url){if(void 0!==window.V_PAGE_INFO){if(
"index"===window.V_PAGE_INFO)return 1;if("subchannel"===window.V_PAGE_INFO)return 3}if("mini2015"===namespace.channel)return 1;if(url.match(/https?:\/\/[^\/]*.qq.com\/+(omn|a)\/+\d{8}/)||url.match(/http:\/\/(video\.)?coral.qq.com\/?/))return 2;if(
void 0!==window.DATA&&window.DATA.hasOwnProperty("catalog1"))return 2;var pos=-1,pos1=url.indexOf("#"),pos2=url.indexOf("?");return(-1<pos1||-1<pos2)&&(-1===(pos=pos2)&&(pos=pos1),url=url.substr(0,pos)),"/"===url.substr(url.length-1)&&(url=url.substr(0,
url.length-1)),"undefined"!=typeof qqlive_client_page_type?qqlive_client_page_type:("/"===url.substr(url.length-1)&&(url=url.substr(0,url.length-1)),0===url.indexOf("https:")&&(url=url.substr(6,url.length)),0===url.indexOf("http:")&&(url=url.substr(5,
url.length)),-1<url.indexOf("index.html")&&(url=url.substr(0,url.indexOf("index.html"))),-1<home.indexOf(url)?1:3)}),home,VISITOR_PING_WITH_HOST_DEFAULT_HOST="p.l.qq.com",VisitorPingWithHost=function(){"use strict";function clearCache(){cache={},
unique_cache=[]}function flush(flushData){flushData.oid.length&&(flushData=function(flushData){if(flushData.oid.length){flushData.oid.length;flushData.pri.toString().replace(/\,/g,"").length===flushData.pri.length&&(flushData.pri=[]),
flushData.tango.toString().indexOf("1")<0&&(flushData.tango=[]);for(var filters=["pctr","targetid","btoid","dtype","btpri","extstr","chl"],i=0,flen=filters.length;i<flen;i++)/[1-9]/.test(flushData[filters[i]].toString())||(flushData[filters[i]]=[])}
return flushData}(flushData),sendPing(format(pingTemplate,flushData)+collectInfo(1),0),namespace.pingSent||(Cps.timeEnd("ping"),(namespace.cdnTest||namespace.resourceInvalid)&&Cps.flush(),namespace.pingSent=!0))}function flushAll(){each(cache,function(v){
flush(v)}),clearCache()}var rurl=encodeURIComLimit(document.referrer,100),pingTemplate=namespace.getProtocol(
"//{host}/p?oid={oid}&cid={cid}&loc={loc}&aver={aver}&soid={soid}&pri={pri}&exp={exp}&pv_type={pv_type}&tango={tango}&dtype={dtype}&targetid={targetid}&btoid={btoid}&pctr={pctr}&btpri={btpri}&extstr={extstr}&index={index}&ping_data={ping_data}&chl={chl}&rurl="+rurl+"&page_type="+PageType(
location.href)),defaultHost=VISITOR_PING_WITH_HOST_DEFAULT_HOST,cache={},unique_cache=[],bufferFlush=buffer(flushAll,2e3);return clearCache(),mix(instance(IPingBase),{append:function(data){var host=data.ping||defaultHost;cache[host]||(cache[host]=function(
host){return{host:host,oid:[],cid:[],loc:[],aver:[],soid:[],pri:[],exp:[],pv_type:[],tango:[],dtype:[],targetid:[],btoid:[],pctr:[],btpri:[],extstr:[],index:[],ping_data:[],chl:[]}}(host));var flag=!1;!function(cache,data){for(var i=0;i<cache.length;i++){
var ok=[],nk=[];for(var p in cache[i])ok.push(p);for(var p in data)nk.push(p);if(ok.length!==nk.length);else{var allsame=!0;for(var p in cache[i])cache[i][p]!==data[p]&&(allsame=!1);if(allsame)return!0}}return!1}(unique_cache,data)?unique_cache.push(data
):flag=!0,-1<data.loc.indexOf(":")&&(data.loc=data.loc.substr(0,data.loc.indexOf(":"))),each(cache[host],function(v,k){flag||"host"===k||v.push(data[k]?data[k]:0)});var cacheData=cache[host],clen=collectInfo(1).length,ncacheData=[];2048<=format(
pingTemplate,cacheData).length+clen?(ncacheData=function(flushData,len){var cacheDataCopy={};return len<0&&(len=flushData.oid.length+len),each(flushData,function(v,k){cacheDataCopy[k]="host"===k?v:v.splice(0,len)}),cacheDataCopy}(cacheData,-1),flush(
ncacheData)):bufferFlush()},flush:flushAll})}(),VisitorPing=namespace.ping=function(){"use strict";return mix(instance(IPingBase),{append:function(data){VisitorPingWithHost.append(data)},flush:function(){VisitorPingWithHost.flush()},touch:function(url){if(
url)if(0===url.indexOf("http://")&&"https:"===window.location.protocol){if("undefined"==typeof HAS_ADD_GLOBAL_REFER){window.HAS_ADD_GLOBAL_REFER=1;var m1=document.createElement("meta");m1.setAttribute("name","referrer"),m1.setAttribute("content","always"),
m1.setAttribute("id","global_refer_setting");var headTag=document.getElementsByTagName("head");headTag&&headTag[0].appendChild(m1)}sendPing(url),setTimeout(function(){var refsetting=document.getElementById("global_refer_setting");refsetting&&(
refsetting.parentNode.removeChild(refsetting),window.HAS_ADD_GLOBAL_REFER=void 0)},5e3)}else sendPing(url)}})}(),getFlashVersion=namespace.getFlashVersion=function(){try{if(navigator.plugins&&0<navigator.plugins.length)return parseInt(
navigator.plugins["Shockwave Flash"].description.split(" ")[2],10);if(void 0===window.ActiveXObject)return 0;var flash;try{flash=new ActiveXObject("ShockwaveFlash.ShockwaveFlash")}catch(e){for(var i=15;5<i;i--)try{flash=new ActiveXObject(
"ShockwaveFlash.ShockwaveFlash."+i);break}catch(e){}}return flash?parseInt(flash.GetVariable("$version").split(" ")[1].split(",")[0],10):0}catch(e){return 0}},browsersniffer=function(uastr){if(!uastr)return"unknown";var pos=-1,ret=(uastr=uastr.toLowerCase(
)).match(/(?:metasr.\d*|qqbrowser.\d*|maxthon.\d*|theworld|lbbrowser|firefox.\d*|opera.\d*|bidubrowser.\d*)/);if(null!==ret)return ret[0].replace(" ","").replace("/","");if(-1<(pos=uastr.indexOf("chrome")))return"chrome"+parseInt(uastr.substr(pos+7,4));if(
-1<(pos=uastr.indexOf("safari")))return"safari";var mpos=uastr.indexOf("msie");if(-1<mpos)return"ie"+parseInt(uastr.substr(mpos+5,2));if(-1<uastr.indexOf("trident")){var rvpos=uastr.indexOf("rv:");if(-1<rvpos)return"ie"+parseInt(uastr.substr(rvpos+3,2))}
return uastr},action_map,PING_TEMPLATE;action_map={expand:1,shrink:2},PING_TEMPLATE=namespace.getProtocol("//dp3.qq.com/richmedia/?action={ACTION}&oid={OID}&loc={LOC}&site={CHANNEL}&ua={UA}&reqid={CID}"),namespace.rmreport=function(option){
var actionNum=action_map[option.action],oid=option.oid||"",loc=option.loc||"";if(!actionNum)throw new Error('[ function:rmreport ] : Invalid value of parameter "action" - '+option.action);sendPing(format(PING_TEMPLATE,{ACTION:actionNum,
OID:encodeURIComponent(oid),LOC:encodeURIComponent(loc),CHANNEL:encodeURIComponent(channel),UA:encodeURIComponent(navigator.userAgent),CID:namespace.Uuids.getReqId()}))};var getFlashObject=namespace.getFlashObject=function(flashId){try{
return window.document[flashId]?window.document[flashId]:document.getElementById(flashId)}catch(e){return 0}},doc,body,evt,px,getDatasetAttr,setDatasetAttr,propertyCache,patterns,setStyle,getStyle;!function(dom,evt,cookie){if(mix(namespace,{dom:dom,
evt:evt,ua:ua,cookie:cookie}),setTimeout(function(){crystal_args.mo_ping_script&&Math.random()<crystal_args.mo_ping_ratio&&importScript(crystal_args.mo_ping_script)},1e3*crystal_args.mo_ping_time_out),ua.gecko){var xhr=new XMLHttpRequest
;window.onbeforeunload=function(){Cps.flush(function(url){xhr.open("GET",url,!1),xhr.send(null)})}}else evt.on(window,"beforeunload",function(){Cps.flush()});evt.ready(function(){if(11<=getFlashVersion()){var flashplayerid=generateId()
;fp11input=dom.createElement({position:"absolute",left:"-1000px",top:"50px",width:"10px","z-index":-1,cursor:"none"},{type:"text",id:flashplayerid,value:""},"input"),(document.body||document.documentElement).appendChild(fp11input)}namespace.dom.addCss([{
selector:'.l_qq_com[id^="NEW_QQCOM"]',rules:"zoom:1"},{selector:"@media screen and (max-width:1440px)",rules:'.l_qq_com[id^="NEW_QQCOM"] {zoom:0.8858}'},{selector:"@media screen and (max-width:1279px)",rules:'.l_qq_com[id^="NEW_QQCOM"] {zoom:0.7206}'}])}),
evt.on(window,"unload",function(){VisitorPing.flush()}),namespace.resource=function(file){return crystal_args.file_path+file},namespace.resource_swf=function(file){return crystal_args.ext_path+file};var getExtension=namespace.getExtension=function(uri){
try{return/\.(\w+)(?:$|\?|\#)/.exec(uri)[1].toLowerCase()}catch(e){return"jpg"}},htmlEncode=(el=document.createElement("pre"),function(str){return el.innerHTML="",el.appendChild(document.createTextNode(str)),el.innerHTML}),el
;namespace.getPlayIndex=function(){return parseInt(cookie.get("ad_play_index"))||Math.floor(100*Math.random())};var display_index=namespace.getPlayIndex();cookie.set("ad_play_index",display_index+1,{expires:1,path:"/"});var fodder_url_data=[],
queue=function(precondition){var preconditioned=!1,precondition_is_running=!1,fns=[];return function(fn){preconditioned?fn():(fns.push(fn),precondition_is_running||(precondition(function(){each(fns,function(f){f()}),preconditioned=!0}),
precondition_is_running=!0))}},afterImportExtension=queue(function(callback){crystal_args.is_debug&&(crystal_args.extension_js_src+="?_="+(new Date).getTime()),importScript(namespace.getProtocol(crystal_args.extension_js_src),callback)}),
NONE=namespace.NONE=1,IMMEDIATELY=namespace.IMMEDIATELY=2,LAZY=namespace.LAZY=3,SELF_PING=namespace.SELF_PING=4,defaultfodderData={basepath:"https://ra.gtimg.com/web/default_fodders/",type:"defaultFodder",storagekey:"crystal_defaultFodder",
version:"20190730",default_index_link:["http://users.qq.com","http://users.qq.com","http://time.qq.com/?pgv_ref=ad","https://news.qq.com/mobile/index.htm"],default_index_count:4,default_qq:{15.2:[{scale:15.2,size:"big",resource_url:"1400x90_[index].png"}],
"12.0":[{scale:12,size:"big",resource_url:"920x75_[index].png"}],10.8:[{scale:10.8,resource_url:"1000x90_[index].png"}],10.22:[{scale:10.22,resource_url:"920x90_[index].png"}],10:[{scale:10,resource_url:"960x90_[index].png"}],8.5:[{scale:8.5,
resource_url:"700x75_[index].png"}],7.7:[{scale:7.7,resource_url:"700x90_[index].png"}],7.3:[{scale:7.3,resource_url:"660x90_[index].png"}],5.3:[{scale:5.3,resource_url:"640x120_[index].png"}],4.8:[{scale:4.8,resource_url:"440x90_[index].png"}],3.57:[{
scale:3.57,resource_url:"280x90_[index].png"}],3.3:[{scale:3.3,resource_url:"280x90_[index].png"}],2.1:[{scale:2.1,resource_url:"240x100_[index].png"}],1.55:[{scale:1.55,resource_url:"300x190_[index].png"}],1.2:[{scale:1.2,
resource_url:"300x250_[index].png"}],1.12:[{scale:1.12,resource_url:"320x285_[index].png"}],"1.0":[{scale:1,resource_url:"250x230_[index].png"}],.7:[{scale:.7,resource_url:"280x320_[index].png"}],.4:[{scale:.4,resource_url:"300x600_[index].png"}],0:[{
scale:0,resource_url:"180x600_[index].png"}]},www:{"12.0":[{scale:12,size:"big",priority:1,resource_url:"https://ra.gtimg.com/web/default_fodders/920x75_www.png",link_to:"https://news.qq.com/mobile/index.htm"}],10.22:[{scale:10.22,priority:1,
resource_url:"https://ra.gtimg.com/web/default_fodders/920x90_www.png",link_to:"https://news.qq.com/mobile/index.htm"}],15.2:[{scale:15.2,priority:1,resource_url:"https://ra.gtimg.com/web/default_fodders/1400x90_www.png",
link_to:"https://news.qq.com/mobile/index.htm"}]},v:[]},pullDefaultData=function(){setTimeout(function(){namespace.importScript("https://ra.gtimg.com/web/default_fodders/defaultFodder.js",function(data){})},2e3)};namespace.loadExternal=function(data){
"defaultFodder"===data.type&&(data.syncFlag=namespace.crystal_args.jsProfileOpen,data.createTime=(new Date).getTime(),namespace.DataStorage.setItem(defaultfodderData.storagekey,JSON.stringify(data)))};var default_fodder_index=0,
default_fodder_datasource="code",default_fodder_local=namespace.DataStorage.getItem(defaultfodderData.storagekey);if(default_fodder_local)try{defaultfodderData=JSON.parse(default_fodder_local),
defaultfodderData.syncFlag!==namespace.crystal_args.jsProfileOpen&&pullDefaultData(),default_fodder_datasource="local";var default_expiredTime=2592e6;(new Date).getTime()-defaultfodderData.createTime>default_expiredTime&&namespace.DataStorage.removeItem(
defaultfodderData.storagekey)}catch(e){namespace.DataStorage.removeItem(defaultfodderData.storagekey)}else pullDefaultData();var retriveFodderList=function(fodderData,runat,channel){var platformData=fodderData["default_"+runat],
channelData=fodderData[channel],ret={};for(var scale in platformData)channelData&&void 0!==channelData[scale]?ret[scale]=platformData[scale].concat(channelData[scale]):ret[scale]=platformData[scale];return ret},retriveScaleList=function(fodderData){
var ret=[];for(var prop in fodderData)ret.push(prop);return ret.sort(function(a,b){return 1*b<1*a?-1:1}),ret},fodderList=retriveFodderList(defaultfodderData,namespace.crystal_args.runat,namespace.channel),scaleList=retriveScaleList(fodderList),
getScale=function(width,height){0==height&&(height=1);for(var s=width/height,i=0;i<scaleList.length;i++)if(s>=scaleList[i])return scaleList[i];return"0"},default_fodder_index=0,fillFodder=function(fodder,defaultfodderData,index,width,height){var ret={}
;return 0===fodder.resource_url.indexOf("http")?(ret.resource_url=fodder.resource_url,ret.link_to=fodder.link_to):(ret.resource_url=defaultfodderData.basepath+namespace.crystal_args.runat+"/"+fodder.resource_url.replace("[index]",index),
ret.link_to=defaultfodderData.default_index_link[index]),ret.oid=100,ret.width=width,ret.height=height,ret.cover=!1,ret},reportFodder=function(defaultFodder,status){
var url="//dp3.qq.com/stdlog?bid=crystal&pid=defaultfodder&host="+location.host+"&cv="+defaultfodderData.version+"&pfv="+default_fodder_datasource+"&uav="+status+"&ref="+document.referrer+"&from="+encodeURIComponent(defaultFodder);sendPing(url)},
getFodderDetail=function(fodderList,index){for(var i=0;i<fodderList.length;i++)if(fodderList[i].hasOwnProperty("priority"))return fodderList[i];return fodderList[0]},getDefaultFodder=function(el){
var index=default_fodder_index++%defaultfodderData.default_index_count;if(dom.hasClass(el,"has_qq_live_default_ad"))return getQqLiveDefaultFodder(el);var sw=parseInt(el.style.width),sh=parseInt(el.style.height),ow=el.offsetWidth,oh=el.offsetHeight,
w=0!==ow||isNaN(sw)?ow:sw,h=0!==oh||isNaN(sh)?oh:sh,fodder=fillFodder(getFodderDetail(fodderList[getScale(w,h)],index),defaultfodderData,index,w,h);return reportFodder(fodder.resource_url,h&&w?"success":"fail"),fodder},getQqLiveDefaultFodder=function(el){
return{resource_url:namespace.getProtocol("//ra.gtimg.com/web/default_fodders/qqliveDefault.jpg"),width:el.offsetWidth,height:el.offsetHeight,cover:!0,link_to:"http://itunes.apple.com/cn/app/id458318329?mt=8"}},getMulticlickurl=function(display_config,el){
var initvars={};if(0!=display_config.click_prefix&&0!=display_config.click_content)for(var click_arr=display_config.click_content.split(","),i=0,len=click_arr.length;i<len;i++){var tmp=click_arr[i].split("|")
;initvars[tmp[0]]=display_config.click_prefix+"seq="+tmp[1]+"&loc="+(el.id||"")}return initvars},getFodderCover=namespace.getFodderCover=function(el){var childNodes=el.childNodes;if(childNodes&&0!=childNodes.length)for(var len=childNodes.length,
i=0;i<len;i++){var currrentChild=childNodes[i];if(dom.hasClass(currrentChild,"a_cover")&&currrentChild.getAttribute("rel"))return currrentChild;var rt=arguments.callee(currrentChild);if(rt)return rt}},hasFilterInParent=function(el){try{
var parent=el.parentNode;return!!parent&&(!!parent.style.filter||hasFilterInParent(parent))}catch(e){return!1}},thirdPartyScriptRenderedOrder={},dic_display={"third_party_script_plus":{ping:LAZY,render:function(config,el){if(config.fodder&&config.fodder[0]
){var ru=config.fodder[0].resource_url,fileName=/.+\/(\w+\.\w+)(?:\?.+)?/g.exec(ru)[1],fileNameArray=fileName.split("."),newFileName=fileNameArray[0]+"_"+config.oid+"_"+config.cid+"."+fileNameArray[1];config.fodder[0].resource_url=ru.replace(fileName,
newFileName),renderFodder(config.fodder[0],el)}}},"third_party_script":{ping:LAZY,render:function(config,el){void 0!==config.display_config.noadicon&&"1"==config.display_config.noadicon?renderFodder(config.fodder[0],el):renderFodder(config.fodder[0],el,
null,null,!0)}},"banner":{ping:LAZY,render:function(config,el){if(0==namespace.getFlashVersion()&&"swf"==namespace.getExtension(config.fodder[0].resource_url))return"none"==el.style.display?void 0:(crystal_args.tiediAdReplaceArr.push(config.loc),
void renderFodder(getDefaultFodder(el),el,null,null,!0));function preprocessFodder(config,el,fodder){config.display_config&&config.display_config.click_prefix&&config.display_config.click_content&&(fodder.initvars=namespace.mix(fodder.initvars,
getMulticlickurl(config.display_config,el))),config.display_config&&1==config.display_config.support_api&&(fodder.initvars=namespace.mix(fodder.initvars,{"token":namespace.getApitoken(config.oid,config.loc)}))}config.dsp_id&&config.dsp_name&&(
config.fodder[0].private_link=config.private_link,config.fodder[0].dsp_name=8<config.dsp_name.length?config.dsp_name.substr(0,8):config.dsp_name,config.fodder[0].privateTag=!0,config.fodder[0].oid=config.oid);function sufprocessBanner(config,el,fodder){
config.display_config&&"center"===config.display_config.loc_pos&&(el.style.width=fodder.width+"px",el.style.marginLeft="auto",el.style.marginRight="auto"),config.display_config&&1==config.display_config.private_setting&&evt.on(el,"mouseover",function(){
var icon=dom.$("private_setting_"+config.oid);if(!icon){(icon=createIcon("private_setting",config.display_config.icon_location||"rt","20px","20px",{"title":"\u9690\u79c1\u8bbe\u7f6e","link_to":"http://setting.snswin.qq.com"})
).id="private_setting_"+config.oid,el.appendChild(icon);function hideIcon(){return setTimeout(function(){el.removeChild(icon)},3e3)}var timer1=hideIcon();evt.on(icon,"mouseover",function(){clearTimeout(timer1)}),evt.on(icon,"mouseout",function(){
timer1=hideIcon()})}});var displayConfig=config.display_config,isCover=!!fodder&&fodder.cover,coverElement=getFodderCover(el);coverElement&&(Cps.registerClick(el,coverElement,config),namespace.evt.on(el,"click",function(){if(
config.clickReportUrlOther&&isArray(config.clickReportUrlOther))for(var i=0;i<config.clickReportUrlOther.length;i++){var item=config.clickReportUrlOther[i];item&&item.url&&namespace.ping.touch(item.url)}})),
displayConfig&&1==displayConfig.support_api&&isCover&&coverElement&&evt.on(coverElement,"click",function(){sendPing(namespace.sns_pingurl(config,"banner_click"))}),displayConfig&&"_self"===displayConfig.target&&coverElement&&(coverElement.target=""),
displayConfig&&displayConfig.pLink&&coverElement&&(coverElement.href="",coverElement.target="",evt.on(coverElement,"click",function(event){event.preventDefault?event.preventDefault():event.returnValue=!1;try{new ActiveXObject(
"QQGAMEDETECT.QQGameDetectCtrl.1");window.location=displayConfig.pLink}catch(e){window.open(fodder.link_to,"_blank")}})),dom.hasClass(el,"check_double_filter")&&isCover&&coverElement&&hasFilterInParent(coverElement)&&(coverElement.style.backgroundColor="",
coverElement.style.filter="",coverElement.style.opacity="")}config.fodder[0]&&(config.fodder[0].display="banner");function render(config){if(namespace.dom.getViewportWidth()>=config.display_config.critical){var index=config.display_config.index_above;if(
banner_flag.index_above)return;banner_flag={index_above:!0,index_below:!1}}else{index=config.display_config.index_below;if(banner_flag.index_below)return;banner_flag={index_above:!1,index_below:!0}}!function(el){for(;el.firstChild;)el.removeChild(
el.firstChild)}(el),preprocessFodder(config,el,config.fodder[index]),renderFodder(config.fodder[index],el,null,null,!0),sufprocessBanner(config,el,config.fodder[index])}var banner_flag={index_above:!1,index_below:!1};if(
config.display_config&&config.display_config.critical)render(config),evt.on(window,"resize",function(){void 0!==namespace.banner_timer&&clearTimeout(namespace.banner_timer),namespace.banner_timer=setTimeout(function(){render(config)},300)});else{!(
config.fodder[0].width<=145&&132<=config.fodder[0].width&&config.fodder[0].height<=120&&100<=config.fodder[0].height)||-1<["js"].indexOf(channel)?(preprocessFodder(config,el,config.fodder[0]),renderFodder(config.fodder[0],el,config.icon,"rb",!0)):(
preprocessFodder(config,el,config.fodder[0]),renderFodder(config.fodder[0],el)),sufprocessBanner(config,el,config.fodder[0])}el.parentNode,el.parentNode.offsetWidth,el.getAttribute("id"),(-1!==el.getAttribute("id").indexOf("QQlive_SP_QLL_Width"
)||el.getAttribute("id").indexOf("QQlive_NN_SP_bf_pl_S_Width")||el.getAttribute("id").indexOf("QQlive_N_SP_HP_minibanner1"))&&el.parentNode.offsetWidth/config.fodder[0].width<1&&(el.style.zoom=el.parentNode.offsetWidth/config.fodder[0].width),evt.on(window
,"resize",function(){el.getAttribute("id"),(-1!==el.getAttribute("id").indexOf("QQlive_SP_QLL_Width")||el.getAttribute("id").indexOf("QQlive_NN_SP_bf_pl_S_Width")||el.getAttribute("id").indexOf("QQlive_N_SP_HP_minibanner1"))&&setTimeout(function(){
el.style.zoom=el.parentNode.offsetWidth/config.fodder[0].width<1?el.parentNode.offsetWidth/config.fodder[0].width:1},300)})}},"adaptive_banner":{ping:IMMEDIATELY,render:function(config,el,el_id,ping){function render(){for(var first_width=parseInt(
namespace.dom.getStyle(el.parentNode,"width"),"10"),i=0;i<config.fodder.length;i++)first_width===config.fodder[i].width&&banner_double_flag!==first_width&&(banner_double_flag=first_width,renderFodder(config.fodder[i],el,null,null,!0))}
var banner_double_flag=0;render(),evt.on(window,"resize",function(){render()})}},"feeds":{ping:NONE,render:function(config,node,ping){var spans=node.getElementsByTagName("span");spans&&0<spans.length&&(spans[0].innerHTML=config.fodder[1].text)
;var imgs=node.getElementsByTagName("img");imgs&&0<imgs.length&&(imgs[0].setAttribute("src",config.fodder[0].resource_url),imgs[0].setAttribute("alt",config.fodder[1].text));var as=node.getElementsByTagName("a");as&&0<as.length&&as[0].setAttribute("href",
config.fodder[0].link_to);var adicon=namespace.dom.createElement({position:"absolute",right:"10px",bottom:0},{src:"//ra.gtimg.com/web/res/aio/feeds_ico.png"},"img");node.appendChild(adicon)}},"focus":{ping:NONE,render:function(config,node,ping){
var spans=node.getElementsByTagName("span");spans&&0<spans.length&&(spans[0].innerHTML=config.fodder[1].text);var imgs=node.getElementsByTagName("img");imgs&&0<imgs.length&&(imgs[0].setAttribute("src",config.fodder[0].resource_url),imgs[0].setAttribute(
"alt",config.fodder[1].text));var as=node.getElementsByTagName("a");as&&0<as.length&&as[0].setAttribute("href",config.fodder[0].link_to);var adicon=namespace.dom.createElement({position:"absolute",right:"2px",bottom:"7px"},{
src:"//ra.gtimg.com/web/res/aio/focus_ico.png"},"img");node.appendChild(adicon)}},"banner_double":{ping:IMMEDIATELY,render:function(config,el,el_id,ping){var banner_double_flag=0,render=function(){for(var first_width=parseInt(namespace.dom.getStyle(
el.parentNode,"width"),"10"),i=0;i<config.fodder.length;i++)first_width===config.fodder[i].width&&banner_double_flag!==first_width&&(banner_double_flag=first_width,renderFodder(config.fodder[i],el,null,null,!0));setTimeout(function(){render()},800)}
;render(),evt.on(window,"resize",function(){void 0!==namespace.banner_double_timer&&clearTimeout(namespace.banner_double_timer),namespace.banner_double_timer=setTimeout(function(){render()},800)})}},"auto":{ping:IMMEDIATELY,render:function(config,el){
namespace.requestDefaultAdData("auto",config,el)}},"default":{ping:NONE,render:function(config,el){el.style.overflow="hidden",renderFodder(getDefaultFodder(el),el)}},"null":{ping:IMMEDIATELY,render:function(config,el){
void 0!==window.crystalInterface&&crystalInterface.noad(config.loc)}},"banner_script_src":{ping:IMMEDIATELY,render:function(config,el){renderFodder(config.fodder[0],el),importScript(config.fodder[1].resource_url)}},"banner_import_monitor_url":{
ping:IMMEDIATELY,render:function(config,el){renderFodder(config.fodder[0],el),importScript(config.monitor_url)}},"h_banner":{ping:SELF_PING,render:function(){function fixedMouse(e,target){var related,type=e.type.toLowerCase();if("mouseover"==type
)related=e.relatedTarget||e.fromElement;else{if("mouseout"!=type)return!0;related=e.relatedTarget||e.toElement}return related&&"xul"!=related.prefix&&!function(p,c){return p.contains?p!=c&&p.contains(c):!!(16&p.compareDocumentPosition(c))}(target,related
)&&related!==target}var IeWindowResizeHook={originalHeight:window.innerHeight||document.documentElement.clientHeight,originalWidth:window.innerWidth||document.documentElement.clientWidth,isResize:function(){
var h=window.innerHeight||document.documentElement.clientHeight,w=window.innerWidth||document.documentElement.clientWidth;return(this.originalHeight!=h||this.originalWidth!=w)&&(this.originalHeight=h,this.originalWidth=w,!0)}},CurrentPageAdMap={}
;window[lib_name].adRequesterCallback=function(adDataArray){function sendPv(adData){var ping_data={loc:adData.loc,cid:adData.cid||0,oid:adData.oid||0,aver:adData.aver||0,soid:adData.soid||0,ping:adData.ping,pri:adData.pri||0,tango:adData.tango||0,
dtype:adData.dtype||0,targetid:adData.targetid||0,pctr:adData.pctr||0,btoid:adData.btoid||0,btpri:adData.btpri||0,extstr:adData.extstr||"",index:adData.index||1,ping_data:adData.ping_data||"",chl:adData.chl||0};1<=ping_data.dtype&&(
ping_data.keywordIds=""!==adData.keywordIds?adData.keywordIds:"",ping_data.whiteListId=""!==adData.whiteListId?adData.whiteListId:"",ping_data.ArticleId=""!==adData.ArticleId?adData.ArticleId:""),VisitorPing.append(ping_data),
adData.monitor_url&&setTimeout(function(){VisitorPing.touch(adData.monitor_url,!0)},1e3),adData.ext_monitor_url&&setTimeout(function(){for(var ping_list=adData.ext_monitor_url.split(" "),i=0,len=(ping_list=ping_list.slice(0,3)).length;i<len;i++
)-1<ping_list[i].indexOf("http://")&&VisitorPing.touch(ping_list[i],!0)},1e3)}var adData=adDataArray[0][0],elId=adData.loc,currentHBanner=CurrentPageAdMap[elId];currentHBanner&&currentHBanner.destroy(),CurrentPageAdMap[elId]=new HBanner(adData,sendPv),
CurrentPageAdMap[elId].init()};var AdRequester_request=function(elId){var lviewUrl=format(crystal_args.lview_template,{loc:elId});importScript(lviewUrl+"&callback="+lib_name+".adRequesterCallback"+("&rot=1&ri=hb_"+elId)+collectInfo(1),function(){},
crystal_args.charset)};function HBanner(adData,sendPv){this.adData=adData,this.sendPv=sendPv}return HBanner.prototype.init=function(){var adData=this.adData;this.adLocationEl=document.getElementById(adData.loc),this.pvCounter=0;var self=this;if(
!this.isNullOrder()){var adContent=document.createElement("div"),picTop=parseInt(dom.getStyle(document.getElementById("picWrap"),"top")),closeButton=(picTop=isNaN(picTop)?9:picTop,this.closeButton=dom.createElement({position:"absolute",top:0,right:0,
margin:picTop+2+"px 2px 0 0","z-index":100},{src:namespace.resource("takeover_close.gif")},"img"));renderFodder(adData.fodder[0],adContent),dom.setStyle(this.adLocationEl,{display:"none",zIndex:100}),this.adLocationEl.appendChild(adContent),
this.adLocationEl.appendChild(closeButton),this.adLocationEl.appendChild(namespace.createAdIcon()),this.addCover(),evt.on(this.adLocationEl,"mouseover",function(e){fixedMouse(e,self.adLocationEl)&&self.removeCover()}),evt.on(this.adLocationEl,"mouseout",
function(e){fixedMouse(e,self.adLocationEl)&&self.addCover()}),evt.on(closeButton,"click",function(){self.close()})}this.resizeFunction=function(){self.resize()},evt.on(window,"resize",this.resizeFunction),setTimeout(function(){var i=hdPic.fn._getUrl()+""
;"1"!=i&&"0"!=i&&self.show()},1e3),namespace.setArea(this.adData.loc,{show:function(){self.show()},hide:function(){self.hide()}})},HBanner.prototype.destroy=function(){this.resizeFunction&&evt.un(window,"resize",this.resizeFunction),this.adLocationEl&&(
namespace.clearArea(this.adData.loc),dom.setStyle(this.adLocationEl,{display:"none"}),this.adLocationEl.innerHTML="")},HBanner.prototype.addCover=function(){var cover=document.getElementById("mengban_"+this.adData.loc);cover||(cover=document.createElement(
"div"),dom.setStyle(cover,{position:"absolute",top:0,left:0,width:"100%",height:"100%",opacity:"0.5",filter:"alpha(opacity=50)",backgroundColor:"white"}),cover.id="mengban_"+this.adData.loc,this.adLocationEl.appendChild(cover))},
HBanner.prototype.removeCover=function(){var cover=document.getElementById("mengban_"+this.adData.loc);cover&&this.adLocationEl.removeChild(cover)},HBanner.prototype.isNullOrder=function(){return this.adData.oid+""=="1"},HBanner.prototype.show=function(){
if(this.is1stOrLast=!1,this.canBeShowed()){if(0===this.pvCounter)this.sendPv&&this.sendPv(this.adData);else if(10===this.pvCounter)return void AdRequester_request(this.adData.loc);this.pvCounter++;var self=this;setTimeout(function(){if(!self.isNullOrder()
){var picTop=parseInt(dom.getStyle(self.sizeReferenceEl,"top")),picHeight=(picTop=isNaN(picTop)?9:picTop,dom.getStyle(self.sizeReferenceEl,"height"));dom.setStyle(self.adLocationEl,{display:"block",height:picHeight,paddingTop:picTop+"px"}),
self.closeButton&&dom.setStyle(self.closeButton,{margin:picTop+2+"px 2px 0 0"})}self.resizeLock=!1},300)}},HBanner.prototype.close=function(){dom.setStyle(this.adLocationEl,{display:"none"}),this.closeTimeCookieName||(
this.closeTimeName="hbanner"+this.adData.loc),DataStorage.setItem(